--
--    Copyright 2009-2026 the original author or authors.
--
--    Licensed under the Apache License, Version 2.0 (the "License");
--    you may not use this file except in compliance with the License.
--    You may obtain a copy of the License at
--
--       https://www.apache.org/licenses/LICENSE-2.0
--
--    Unless required by applicable law or agreed to in writing, software
--    distributed under the License is distributed on an "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--    See the License for the specific language governing permissions and
--    limitations under the License.
--

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100),
    email      VARCHAR(255) UNIQUE,
    status     VARCHAR(20) DEFAULT 'ACTIVE',
    age        INTEGER,
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP
);

-- 1. Inserting full records with explicit timestamps
INSERT INTO users (name, email, status, age, created_at)
VALUES ('Alice Smith', 'alice@example.com', 'ACTIVE', 28, '2023-05-10 10:00:00');

INSERT INTO users (name, email, status, age, created_at)
VALUES ('Charlie Brown', 'charlie@example.com', 'PENDING', 22, '2023-11-01 14:30:00');

INSERT INTO users (name, email, status, age, created_at)
VALUES ('Diana Prince', 'diana@example.com', 'INACTIVE', 35, '2022-01-15 09:15:00');

-- 2. Relying on default values
-- Because 'status' defaults to 'ACTIVE' and 'created_at' defaults to CURRENT_TIMESTAMP,
-- we can omit them from the insert statement. The ID is also auto-generated.
INSERT INTO users (name, email, age)
VALUES ('Bob Jones', 'bob@example.com', 42);

-- 3. Bulk Insert
-- HSQLDB supports inserting multiple rows in a single statement.
INSERT INTO users (name, email, status, age, created_at)
VALUES ('Evan Wright', 'evan@example.com', 'ACTIVE', 45, '2024-01-20 08:00:00'),
       ('Fiona Gallagher', 'fiona@example.com', 'PENDING', 29, '2024-02-15 11:45:00'),
       ('George Martin', 'george@example.com', 'BANNED', 55, '2023-08-30 16:20:00');