/*
 *    Copyright 2009-2026 the original author or authors.
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *       https://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.apache.ibatis.submitted.cache;

import java.io.IOException;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.Objects;

import org.apache.ibatis.BaseDataTest;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.logging.stdout.StdOutImpl;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

/**
 * the test case that explain the usage of mybatis cache. refer to this article:
 * <a href="https://tech.meituan.com/2018/01/19/mybatis-cache.html">...</a>
 * <p>
 * condition that tow SQL is same:
 *
 * <pre>
 * Statement Id + Offset + Limit + Sql + Params
 * </pre>
 */
class ExtraCacheTest {

  private static final String STUDENT_SCRIPT = """
      DROP TABLE IF EXISTS student;
      CREATE TABLE student (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
        name VARCHAR(200),
        age TINYINT
      );
      INSERT INTO student (id, name, age) VALUES (1, 'A', 16);
      INSERT INTO student (id, name, age) VALUES (2, 'B', 16);
      INSERT INTO student (id, name, age) VALUES (3, 'C', 16);
      INSERT INTO student (id, name, age) VALUES (4, 'D', 16);
      """;

  private static final String CLASS_INFO_SCRIPT = """
      DROP TABLE IF EXISTS class;
      CREATE TABLE class (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
        name VARCHAR(20)
      );
      INSERT INTO class (id, name) VALUES (1, 'Class One');
      INSERT INTO class (id, name) VALUES (2, 'Class Two');
      """;

  private static final String CLASS_ROOM_SCRIPT = """
      DROP TABLE IF EXISTS classroom;
      CREATE TABLE classroom (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
        class_id INTEGER,
        student_id INTEGER
      );
      INSERT INTO classroom (id, class_id, student_id) VALUES (1,1,1);
      INSERT INTO classroom (id, class_id, student_id) VALUES (2,1,2);
      INSERT INTO classroom (id, class_id, student_id) VALUES (3,2,3);
      INSERT INTO classroom (id, class_id, student_id) VALUES (4,2,4);
      """;

  private SqlSessionFactory buildSqlSessionFactory() throws IOException, SQLException {
    SqlSessionFactory factory = BaseDataTest.createDefaultHsqlDbSqlSessionFactory("cache_test");
    factory.getConfiguration().setLogImpl(StdOutImpl.class); // print sql in console
    factory.getConfiguration().addMapper(StudentMapper.class);
    factory.getConfiguration().addMapper(ClassMapper.class);
    BaseDataTest.runScriptSql(factory, STUDENT_SCRIPT);
    BaseDataTest.runScriptSql(factory, CLASS_INFO_SCRIPT);
    BaseDataTest.runScriptSql(factory, CLASS_ROOM_SCRIPT);
    return factory;
  }

  /**
   * 1-level cache enabled, session-level scope and call getStudentById three times Only the first query actually
   * accessed the database, while subsequent queries utilized the first-level cache
   */
  @Test
  void shouldHitLevel1Cache() throws SQLException, IOException {
    try (SqlSession sqlSession = buildSqlSessionFactory().openSession(true)) {
      StudentMapper studentMapper = sqlSession.getMapper(StudentMapper.class);
      Student stu1 = studentMapper.getStudentById(1);
      // will hit cache
      Student stu2 = studentMapper.getStudentById(1);
      // will hit cache
      Student stu3 = studentMapper.getStudentById(1);
      Assertions.assertEquals(stu1, stu2);
      Assertions.assertEquals(stu1, stu3);
      Assertions.assertEquals(stu2, stu3);
    }
  }

  /**
   * Added modification operations on the database to verify whether the first-level cache becomes invalid if database
   * modifications occur during a single session
   */
  @Test
  void shouldLevel1CacheInvalidWhenUpdated() throws SQLException, IOException {
    try (SqlSession sqlSession = buildSqlSessionFactory().openSession(true)) {
      StudentMapper studentMapper = sqlSession.getMapper(StudentMapper.class);

      studentMapper.getStudentById(1);
      studentMapper.addStudent(buildStudent());

      // After modifying the operation, the same query was executed and the database was queried,
      // resulting in the invalidation of the first level cache
      studentMapper.getStudentById(1);
    }
  }

  private Student buildStudent() {
    Student student = new Student();
    student.setName("E");
    student.setAge(20);
    return student;
  }

  /**
   * Open two SQL Sessions, query data in SQL Session 1 to validate the first level cache, update the database in SQL
   * Session 2, and verify that the first level cache is only shared within the database session.
   */
  @Test
  void shouldLevel1CacheNotSharedBetweenSession() throws SQLException, IOException {
    final SqlSessionFactory factory = buildSqlSessionFactory();

    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true)) {
      StudentMapper studentMapper1 = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);
      Student stu1 = studentMapper1.getStudentById(1);
      Student stu2 = studentMapper1.getStudentById(1);
      Assertions.assertEquals(stu1, stu2);

      studentMapper2.updateStudentName("AA", 1);
      Student stu3 = studentMapper1.getStudentById(1);
      // dirty
      Assertions.assertEquals(stu1.getName(), stu3.getName());
      Student stu4 = studentMapper1.getStudentById(1);
      Assertions.assertEquals(stu3, stu4);
      // Level 1 cache is only shared within the database session

      Student stu5 = studentMapper2.getStudentById(1);
      Assertions.assertEquals("AA", stu5.getName());
      Assertions.assertNotEquals("AA", stu3.getName());
      Assertions.assertNotEquals("AA", stu4.getName());
    }
  }

  // level2 cache

  @Test
  void shouldHitLevel2Cache() throws SQLException, IOException {
    SqlSessionFactory factory = buildSqlSessionFactory();
    factory.getConfiguration().setCacheEnabled(true); // enable level2 cache
    // <setting name="cacheEnabled" value="true"/>
    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true)) {
      StudentMapper studentMapper1 = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);
      Student stu1 = studentMapper1.getStudentById(1);
      // will hit cache
      Student stu2 = studentMapper2.getStudentById(1);
      Assertions.assertEquals(stu1, stu2);
    }
  }

  @Test
  void shouldLevel2CacheInvalidWhenCommitted() throws SQLException, IOException {
    SqlSessionFactory factory = buildSqlSessionFactory();
    factory.getConfiguration().setCacheEnabled(true); // enable level2 cache
    // <setting name="cacheEnabled" value="true"/>
    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true)) {
      StudentMapper studentMapper1 = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);

      // first query
      Student stu1 = studentMapper1.getStudentById(1);
      // commit will flush cache
      sqlSession1.commit();
      // will not hit cache
      Student stu2 = studentMapper2.getStudentById(1);
      Assertions.assertEquals(stu1, stu2);
    }
  }

  /**
   * Test whether the update operation will refresh the second level cache under this namespace.
   */
  @Test
  void shouldLevel2CacheInvalidWhenUpdated() throws SQLException, IOException {
    SqlSessionFactory factory = buildSqlSessionFactory();
    factory.getConfiguration().setCacheEnabled(true); // enable level2 cache
    // <setting name="cacheEnabled" value="true"/>
    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true);
        SqlSession sqlSession3 = factory.openSession(true)) {
      StudentMapper studentMapper1 = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);
      StudentMapper studentMapper3 = sqlSession3.getMapper(StudentMapper.class);

      studentMapper1.getStudentById(1);
      sqlSession1.commit();
      studentMapper2.getStudentById(1);

      studentMapper3.updateStudentName("AA", 1);
      sqlSession3.commit();

      // will not hit cache
      studentMapper2.getStudentById(1);
    }
  }

  /**
   * Verify that MyBatis' L2 cache is not suitable for mapping files with multiple table queries. Usually, we create
   * separate mapping files for each single table. Since MyBatis' L2 cache is based on namespaces, the namespace where
   * multi table query statements are located cannot sense the modifications made by statements in other namespaces to
   * the tables involved in the multi table query, causing dirty data problems.
   */
  @Test
  void shouldLevel2CacheNotSharedInDifferentNamespace() throws SQLException, IOException {
    SqlSessionFactory factory = buildSqlSessionFactory();
    factory.getConfiguration().setCacheEnabled(true); // enable level2 cache
    // <setting name="cacheEnabled" value="true"/>
    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true);
        SqlSession sqlSession3 = factory.openSession(true)) {
      StudentMapper studentMapper1 = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);
      ClassMapper classMapper = sqlSession3.getMapper(ClassMapper.class);

      studentMapper1.getStudentByIdWithClassInfo(1);
      sqlSession1.close();
      studentMapper2.getStudentByIdWithClassInfo(1);

      classMapper.updateClassName("Class 3", 1);
      sqlSession3.commit();
      studentMapper2.getStudentByIdWithClassInfo(1);
    }
  }

  /**
   * <setting name="localCacheScope" value="SESSION"/> <setting name="cacheEnabled" value="true"/> this will solve the
   * problem in {@link ExtraCacheTest#shouldLevel2CacheNotSharedInDifferentNamespace()}
   *
   * @see ExtraCacheTest#shouldLevel2CacheNotSharedInDifferentNamespace()
   */
  @Test
  public void testCacheWithDifferentNamespaceWithCacheRef() throws Exception {
    SqlSessionFactory factory = buildSqlSessionFactory();
    // <setting name="cacheEnabled" value="true"/>
    factory.getConfiguration().setCacheEnabled(true); // enable level2 cache

    try (SqlSession sqlSession1 = factory.openSession(true); SqlSession sqlSession2 = factory.openSession(true);
        SqlSession sqlSession3 = factory.openSession(true)) {
      StudentMapper studentMapper = sqlSession1.getMapper(StudentMapper.class);
      StudentMapper studentMapper2 = sqlSession2.getMapper(StudentMapper.class);
      ClassMapper classMapper = sqlSession3.getMapper(ClassMapper.class);

      studentMapper.getStudentByIdWithClassInfo(1);
      sqlSession1.close();

      studentMapper2.getStudentByIdWithClassInfo(1);

      classMapper.updateClassName("Class 3", 1);
      sqlSession3.commit();

      // will hit cache
      studentMapper2.getStudentByIdWithClassInfo(1);
    }
  }
}

@CacheNamespace // same as <cache> in XML.
// @CacheNamespaceRef(StudentMapper.class)
interface ClassMapper {

  @Update("UPDATE class SET name = #{name} WHERE id = #{id}")
  int updateClassName(@Param("name") String className, @Param("id") int id);
}

@CacheNamespace
interface StudentMapper {

  @Select("SELECT id,name,age FROM student WHERE id = #{id}")
  Student getStudentById(int id);

  @Insert("INSERT INTO student(name,age) VALUES(#{name}, #{age})")
  int addStudent(Student student);

  @Update("UPDATE student SET name = #{name} WHERE id = #{id}")
  int updateStudentName(@Param("name") String name, @Param("id") int id);

  @Select("SELECT  s.id,s.name,s.age,class.name as className " + "        FROM classroom c "
      + "        JOIN student s ON c.student_id = s.id " + "        JOIN class ON c.class_id = class.id "
      + "        WHERE s.id = #{id};")
  Student getStudentByIdWithClassInfo(int id);
}

/**
 * <pre>
 * --
 * DROP TABLE IF EXISTS class;
 * --
 * CREATE TABLE class (
 *   id int(11) unsigned NOT NULL AUTO_INCREMENT,
 *   name varchar(20) COLLATE utf8_bin DEFAULT NULL,
 *   PRIMARY KEY (id)
 * ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
 *
 * INSERT INTO class (id, name) VALUES (1,'一班'),(2,'二班');
 * </pre>
 */
class ClassInfo {

  private int classId;

  private String className;

  @Override
  public String toString() {
    return "Class{" + "classId=" + classId + ", className='" + className + '\'' + '}';
  }

  public int getClassId() {
    return classId;
  }

  public void setClassId(int classId) {
    this.classId = classId;
  }

  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }
}

/**
 * DROP TABLE IF EXISTS student; CREATE TABLE student ( id int(11) unsigned NOT NULL AUTO_INCREMENT, name varchar(200)
 * COLLATE utf8_bin DEFAULT NULL, age tinyint(3) unsigned DEFAULT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB
 * AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COLLATE=utf8_bin; INSERT INTO student (id, name, age) VALUES
 * (1,'点点',16),(2,'平平',16),(3,'美美',16),(4,'团团',16);
 */
class Student implements Serializable {

  private Integer id;

  private String name;

  private Integer age;

  private String className;

  public String getClassName() {
    return className;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Integer getAge() {
    return age;
  }

  public void setAge(Integer age) {
    this.age = age;
  }

  @Override
  public String toString() {
    return "Student{" + "id=" + id + ", name='" + name + '\'' + ", age=" + age + ", className='" + className + '\''
        + '}';
  }

  @Override
  public boolean equals(Object object) {
    if (object == null || getClass() != object.getClass())
      return false;
    Student student = (Student) object;
    return Objects.equals(id, student.id) && Objects.equals(name, student.name) && Objects.equals(age, student.age)
        && Objects.equals(className, student.className);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, age, className);
  }
}
